name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the extension
        run: npm run compile

      - name: Package the extension
        run: npm run package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload VSIX file
        uses: actions/upload-artifact@v3
        with:
          name: vscode-extension
          path: '**/*.vsix'

      - name: Deploy to Marketplace
        run: |
          echo "Deploying to the marketplace..."
          # Add your deployment script or command here
          # For example, using vsce to publish the extension
          npx vsce publish --pat ${{ secrets.VSCE_PAT }}